port: ":9090"
enable_toon: false

telemetry:
  endpoint: ""
  insecure: true

servers:
  - name: zentao
    schema_url: "https://b7du.corp.cc/zentao-openapi.json"
    base_url: "https://b7du.corp.cc/api.php/v1"
    token: "22f73f5fc926a1515e1f27d752f494d4"
    allow:
      - methods: ["GET", "POST", "PUT", "DELETE"]
        regex: ".*"
    block: []